AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template equivalent to the provided Terraform configuration for creating a Route Table.

Parameters:
  Region:
    Type: String
    Description: Region where to create resources
    Default: "ap-northeast-1"
  VpcId:
    Type: String
    Description: VPC ID
  ResourceName:
    Type: String
    Description: Resource name
    Default: "example-rt"

Resources:
  RouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VpcId
      Tags:
        - Key: Name
          Value: !Ref ResourceName

Outputs:
  RouteTableId:
    Description: The ID of the created Route Table
    Value: !Ref RouteTable
