AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template equivalent to the provided Terraform configuration for creating an Internet Gateway.

Parameters:
  VpcId:
    Type: String
    Description: VPC ID

Resources:
  InternetGateway:
    Type: AWS::EC2::InternetGateway

  AttachInternetGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref VpcId
      InternetGatewayId: !Ref InternetGateway

Outputs:
  IgwId:
    Description: The ID of the Internet Gateway
    Value: !Ref InternetGateway
