AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template equivalent to the provided Terraform configuration for creating an EC2 instance and outputting its public IP.

Parameters:
  KeyPairParameter:
    Type: AWS::SSM::Parameter::Value<String>
    Description: Get ssh key text
    Default: "/ec2/keypair/key-000"

Outputs:
  SshKeyText:
    Description: SSH Key file
    Value: !Ref KeyPairParameter
