AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template equivalent to the provided Terraform configuration for creating an egress Security Group Rule.

Parameters:
  SecurityGroupId:
    Type: String
    Description: ID of the security group
  CidrBlock:
    Type: String
    Description: IPv4 CIDR range for the egress rule
  FromPort:
    Type: Number
    Description: Starting port for the egress rule
  ToPort:
    Type: Number
    Description: Ending port for the egress rule
  Protocol:
    Type: String
    Description: Protocol for the egress rule (e.g., tcp, udp, icmp)

Resources:
  SecurityGroupEgressRule:
    Type: AWS::EC2::SecurityGroupEgress
    Properties:
      GroupId: !Ref SecurityGroupId
      CidrIp: !Ref CidrBlock
      FromPort: !Ref FromPort
      ToPort: !Ref ToPort
      IpProtocol: !Ref Protocol

Outputs:
  SecurityGroupRuleId:
    Description: The security group ID associated with the rule
    Value: !Ref SecurityGroupEgressRule
