Parameters:
  Subnet1Id: 
    Type: String
  Subnet2Id: 
    Type: String
  SecurityGroupId: 
    Type: String
  DBName: 
    Type: String
  DBUsername: 
    Type: String
  DBPassword: 
    Type: String
    NoEcho: true

Outputs:
  Endpoint:
    Value: !GetAtt DBInstance.Endpoint.Address

Resources:
  DBSubnetGroup:
    Type: 'AWS::RDS::DBSubnetGroup'
    Properties:
      DBSubnetGroupDescription: 'Example DB subnet group'
      SubnetIds:
        - !Ref Subnet1Id
        - !Ref Subnet2Id

  DBInstance:
    Type: 'AWS::RDS::DBInstance'
    Properties:
      DBName: !Ref DBName
      Engine: 'mariadb'
      EngineVersion: '11.4.3'
      DBInstanceClass: 'db.t3.micro'
      AllocatedStorage: 20
      StorageType: 'gp2'
      PubliclyAccessible: false
      MultiAZ: true
      DBSubnetGroupName: !Ref DBSubnetGroup
      VPCSecurityGroups:
        - !Ref SecurityGroupId
      MasterUsername: !Ref DBUsername
      MasterUserPassword: !Ref DBPassword
    DeletionPolicy: "Delete"
