AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template equivalent to the provided Terraform configuration for creating a Route.

Parameters:
  Region:
    Type: String
    Description: Region where to create resources
    Default: "ap-northeast-1"
  RouteTableId:
    Type: String
    Description: Route Table ID
  DestinationCidrBlock:
    Type: String
    Description: The IPv4 CIDR block for the Route
    Default: "0.0.0.0/0"
  GatewayId:
    Type: String
    Description: The ID of the gateway (such as an Internet Gateway or NAT Gateway)
    Default: ""

Resources:
  ExampleRoute:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref RouteTableId
      DestinationCidrBlock: !Ref DestinationCidrBlock
      GatewayId: !Ref GatewayId

Outputs:
  RouteId:
    Description: The ID of the created Route
    Value: !Ref ExampleRoute
