AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template equivalent to the provided Terraform configuration for creating an Internet Gateway.

Parameters:
  Region:
    Type: String
    Description: Region where to create resources
    Default: "ap-northeast-1"
  VpcId:
    Type: String
    Description: VPC ID

Resources:
  ExampleInternetGateway:
    Type: AWS::EC2::InternetGateway

  AttachInternetGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref VpcId
      InternetGatewayId: !Ref ExampleInternetGateway

Outputs:
  IgwId:
    Description: The ID of the Internet Gateway
    Value: !Ref ExampleInternetGateway
