AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template equivalent to the provided Terraform configuration for creating an ingress Security Group Rule.

Parameters:
  SecurityGroupId:
    Type: String
    Description: ID of the security group
  CidrBlock:
    Type: String
    Description: IPv4 CIDR range for the ingress rule
  FromPort:
    Type: Number
    Description: Starting port for the ingress rule
  ToPort:
    Type: Number
    Description: Ending port for the ingress rule
  Protocol:
    Type: String
    Description: Protocol for the ingress rule (e.g., tcp, udp, icmp)

Resources:
  SecurityGroupIngressRule:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId: !Ref SecurityGroupId
      CidrIp: !Ref CidrBlock
      FromPort: !Ref FromPort
      ToPort: !Ref ToPort
      IpProtocol: !Ref Protocol

Outputs:
  SecurityGroupRuleId:
    Description: The security group ID associated with the rule
    Value: !Ref SecurityGroupIngressRule
