- name: Retrieve SSM parameter and save to local file using ssm_parameter_store
  hosts: localhost
  connection: local
  gather_facts: no

  tasks:
    - name: Save SSM parameter value to a local file
      copy:
        content: "{{ keypair_value }}"
        dest: "{{ local_file_path }}"

    - name: Change file permissions
      ansible.builtin.file:
        path: "{{ local_file_path }}"
        mode: '0600'


- name: Setup WordPress with HTTPD and PHP
  hosts: wordpress-server
  gather_facts: no
  become: yes
  vars:
    ansible_user: ec2-user
    ansible_ssh_private_key_file: "{{ local_file_path }}"

  tasks:
    - name: Install httpd and wget
      yum:
        name:
          - httpd
          - wget
        state: present

    - name: Install EPEL repository using amazon-linux-extras
      command: "amazon-linux-extras enable php8.2"

    - name: Clean YUM metadata
      command: "yum clean metadata"

    - name: Install PHP packages
      yum:
        name:
          - php-cli
          - php-pdo
          - php-fpm
          - php-json
          - php-mysqlnd
        state: present

    - name: Install PHP extra packages
      yum:
        name:
          - php
          - php-gd
          - php-mbstring
          - php-opcache
          - php-xml
          - php-common
        state: present

    - name: Download latest WordPress
      get_url:
        url: https://ja.wordpress.org/latest-ja.tar.gz
        dest: /var/www/html/latest.tar.gz

    - name: Extract WordPress
      unarchive:
        src: /var/www/html/latest.tar.gz
        dest: /var/www/html/
        remote_src: yes
        extra_opts: --strip-components=1

    - name: Copy wp-config-sample.php to wp-config.php
      copy:
        src: /var/www/html/wp-config-sample.php
        dest: /var/www/html/wp-config.php
        remote_src: yes

    - name: Update wp-config.php with database name
      replace:
        path: /var/www/html/wp-config.php
        regexp: 'database_name_here'
        replace: "{{ db_name }}"

    - name: Update wp-config.php with database username
      replace:
        path: /var/www/html/wp-config.php
        regexp: 'username_here'
        replace: "{{ db_username }}"

    - name: Update wp-config.php with database password
      replace:
        path: /var/www/html/wp-config.php
        regexp: 'password_here'
        replace: "{{ db_password }}"

    - name: Update wp-config.php with database endpoint
      replace:
        path: /var/www/html/wp-config.php
        regexp: 'localhost'
        replace: "{{ db_endpoint }}"

    - name: Enable and start httpd service
      systemd:
        name: httpd
        enabled: yes
        state: started
